version: '3.8'

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9093:9090"  # Mengekspos port 9090 di host dan container
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: npm run dev
